language: python
python:
  - "3.9"
install:
  - pip install -r requirements.txt
  - pip install black codecov coverage
script:
  - black --check entrypoint.py sphinx_action tests
  - coverage run --omit="*/tests*" -m unittest
after_success:
  - codecov
